# this is a sample config for projects that are using deployctl
# copy this config file to your project's root and rename it to deployctl.conf
# then, run deployctl to run all aspects of the tool

# core info
core {
    project_name = "name"
    email_address = "your@email.com"

    # paste your setup command here i.e. python3 -m venv .venv && source .venv/bin/activate && pip install -r requirements.txt
    setup_command = "python3 -m venv .venv && source .venv/bin/activate && pip install -r requirements.txt"

    # paste your start command here i.e. gunicorn, npm, etc.
    start_command = "gunicorn --workers=4 --bind=0.0.0.0:8000 myapp:app"
    
    # docker or linux
    how_to_run = "docker" # only put docker or linux here

    # path for project
    path_for_project = "~/apps/"

    # port your app listens on inside the container (used for docker run -p PORT:PORT)
    # this should match whatever port your nginx config's proxy_pass points at
    port = 3000
}

lint {
    # this is the path to the folder with your unit tests
    unit_test_folder = "/path/to/tests"

    # this is the command used to run the unit tests
    # must be defined for the language you're using
    unit_test_command = "pytest"
}

# this is the domain for your web application
# we will use an nginx reverse proxy to serve your application on this domain
# ensure a dns record is registered for this domain and points to your vps' ip address
web {
    nginx_config_filename = "nginx.conf"
    domain = "domain.com"
}