# this is a sample config for projects that are using deployctl
# copy this config file to your project's root and rename it to deployctl.conf
# then, run deployctl to run all aspects of the tool

lint {
    # this is the path to the folder with your unit tests
    unit_test_folder = "/path/to/tests"

    # this is the command used to run the unit tests
    # must be defined for the language you're using
    unit_test_command = "pytest"
}

# this is the domain for your web application
# we will use an nginx reverse proxy to serve your application on this domain
# ensure a dns record is registered for this domain and points to your vps' ip address
web {
    domain = "domain.com"
}